# config_version=4
mode:
  start_events: modestartmade_hit
  priority: 200


sound_player:
    mode_escape_started:
      hyrulecastle:
        loops: -1
        volume: 0.5
      rainin:
        loops: 3
        volume: 0.5
     
